backend:
  url: ${BACKEND_API_URL}

pdf:
  csv:
    link: ${CSV_LINK}
hour-rate:
  json:
    link: ${JSON_LINK}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

application:
  cors:
    origins: ${CORS_LINKS}
